openapi: 3.0.3
info:
  title: Тестовое Laravel - Qberry (OpenAPI 3.0)
  contact:
    email: sulimovrg@gmail.com
  version: 0.1.0
servers:
  - url: http://localhost:8002/api
tags:
  - name: locations
    description: Get info about locations
  - name: calculate
    description: Calculate availability of blocks, price of product storage
  - name: book
paths:
  /locations:
    get:
      tags:
        - locations
      summary: Get list of available locations
      description: Get a list of available locations with information about the number of free blocks in each
      operationId: getLocations
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Location'
  /calculate:
    post:
      tags:
        - calculate
      summary: Add a new pet to the store
      description: Add a new pet to the store
      operationId: addPet
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Calculator'
          application/xml:
            schema:
              $ref: '#/components/schemas/Calculator'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Calculator'
        required: true
      responses:
        '200':
          description: Successful operation
        '405':
          description: Invalid input
components:
  schemas:
    Location:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Toronto
        rooms:
          type: array
          xml:
            wrapped: true
          items:
            $ref: '#/components/schemas/Room'
        total_blocks:
          type: integer
          format: int64
          example: 2400
        total_available_blocks:
          type: integer
          format: int64
          example: 2000
      xml:
        name: location
    Room:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        temperature:
          type: integer
          example: -4
        blocks:
          type: integer
          example: 800
        available_blocks:
          type: integer
          example: 600
      xml:
        name: room
    Calculator:
      type: object
      properties:
        location_id:
          type: integer
          format: int32
          example: 1
        temperature:
          type: integer
          format: int32
          example: -4
        volume:
          type: integer
          format: int32
          example: 200
        date_from:
          type: string
          format: date
        date_to:
          type: string
          format: date
      xml:
        name: order
